### ISSUE TITLE
Nav object typo

### ISSUE THREAD

**Issue by arleym** [carpages/gemini-css#3]
I think there's a typo line 41 the nav partial. It's in a line to fix an IE8 bug. CSS Lint found the "\9"in the output!

https://github.com/carpages/gemini-css/blob/master/objects/_nav.scss#L42

I wonder if this line of CSS should be in a "If supporting IE8" flag!

**Comment by mattdrose** [comment]
\9 is a common IE hack. There's no conditional flag for IE8, but I'm sure this project will eventually drop IE8 all together.

As for the CSSLint issue, it looks like there's an open ticket for this issue with no solution :/

CSSLint/parser-lib#21
